[package]
name = "sea-orm-migration-timestamps"
version = "0.1.0"
edition = "2021"

[features]
default = ["postgres"]
# default = ["mysql"]
# default = ["sqlite"]
postgres = []
mysql = []
sqlite = []

[dependencies]
cfg-if = "1.0.0"
sea-orm-migration = "0.11.3"
